name: Run Makefile into PSCore

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5.9'

    - name: Install dependencies
      run: |
        brew install make

    - name: Run Make
      run: |
        make all
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.MY_PERSONAL_TOKEN }}
        publish_dir: ./docs
