name: Run Makefile into PSCore

env:
  SWIFT_VERSION: 5.9
  PROJECT_NAME: PSCore

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '$SWIFT_VERSION'

    - name: Install dependencies
      run: |
        brew install make

    - name: Run Make
      run: |
        make all
